# Generated by Django 5.2.4 on 2026-08-06 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_task_archive_and_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('task_assigned', 'Task Assigned'), ('deadline_reminder', 'Deadline Reminder'), ('task_overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('new_message', 'New Message')], max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(blank=True, max_length=120, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apps.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='apps.task')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', 'created_at'], name='apps_notifi_recipie_8f0035_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('event_key__isnull', False)), fields=('recipient', 'event_key'), name='unique_notification_event_per_recipient')],
            },
        ),
    ]
