# Generated by Django 5.2.4 on 2026-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['department', 'starts_at'], name='event_dept_starts_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_deleted', 'created_at'], name='msg_conv_del_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department', 'is_archived', 'status'], name='task_dept_arch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['department', 'is_archived', 'due_date'], name='task_dept_arch_due_idx'),
        ),
    ]
