# Generated by Django 5.2.4 on 2026-09-25 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_report_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITaskRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_key', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'request_key'), name='unique_ai_task_request')],
            },
        ),
    ]
